site_name: Hyperion Documentation
copyright: Hyperion History API Documentation

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

repo_name: 'eosrio/hyperion-history-api'
repo_url: 'https://github.com/eosrio/hyperion-history-api'

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  - Providers:
      - Getting Started : providers/get-started.md
      - Hyperion Installation:
          - WSL2 Pre-configuration: providers/install/wsl2.md
          - Automated Install Script: providers/install/auto_install.md
          - Manual Installation: providers/install/manual_install.md
          - Docker: providers/install/docker.md
      - Hyperion Configuration:
          - Configuration: providers/setup/hyperion_configuration.md
          - Connections Reference: providers/setup/connections.md
          - Chain Config Reference: providers/setup/chain.md
      - Updating: providers/update.md
  - Users / Developers:
      - Getting Started: dev/howtouse.md
      - Stream Client: dev/stream_client.md
      - Endpoint List: dev/endpoint.md
  - API Reference:
      - v2: api/v2.md
      - v1 compatible: api/v1.md
  - Troubleshooting:
      - Repair: help/repair.md
      - Kibana: help/kibana.md
      - RabbitMQ: help/rabbit.md
      - FAQ: help/faq.md

plugins:
  - social
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'


theme:
  name: 'material'
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - navigation.footer
    - search.suggest
    - search.highlight
  language: en
  palette:
    primary: 'light blue'
    accent: 'orange'
  logo: 'assets/img/simplified_logo.svg'
  favicon: 'assets/img/icon.png'
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra:
  generator: false
  analytics:
    provider: google
    property: G-N6WF1VPFSH
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/eosrio/hyperion-history-api'
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/eosrio/hyperion-docs'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/eosriobrazil'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/EOSHyperion'
