site_name: Hyperion Documentation
site_url: https://hyperion.docs.eosrio.io/
site_description: Scalable Full History API Solution for Antelope (former EOSIO) based blockchains.
copyright: Hyperion History API Documentation
repo_name: 'eosrio/hyperion-history-api'
repo_url: 'https://github.com/eosrio/hyperion-history-api'


markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  - Providers:
      - Getting Started : providers/get-started.md
      - Hyperion Installation:
          - WSL2 Pre-configuration: providers/install/wsl2.md
          - Automated Install Script: providers/install/auto_install.md
          - Manual Installation: providers/install/manual_install.md
          - Docker: providers/install/docker.md
      - Hyperion Configuration:
          - Configuration: providers/setup/hyperion_configuration.md
          - Connections Reference: providers/setup/connections.md
          - Chain Config Reference: providers/setup/chain.md
          - Connect Provider to QRY: providers/setup/qry_connection.md
      - Hyperion CLI Tools:
          - Config Tool (hyp-config): providers/cli-tools/hyp-config.md
          - Indexer Control (hyp-control): providers/cli-tools/hyp-control.md
          - Elasticsearch Config Tool (hyp-es-config): providers/cli-tools/hyp-es-config.md
          - Index Repair (hyp-repair): providers/cli-tools/hyp-repair.md
      - Updating: providers/update.md
      - Troubleshooting:
          - Kibana: providers/help/kibana.md
          - RabbitMQ: providers/help/rabbit.md
          - MongoDB: providers/help/mongodb.md
      - Plugins:
          - Lightweight Explorer: providers/plugins/explorer.md
  - Users / Developers:
      - Getting Started: dev/howtouse.md
      - Stream Client (v3.6+):
          - Introduction: dev/stream_client/index.md
          - Getting Started: dev/stream_client/getting-started.md
          - Client Configuration: dev/stream_client/configuration.md
          - Streaming Actions: dev/stream_client/streaming-actions.md
          - Streaming Table Deltas: dev/stream_client/streaming-deltas.md
          - Handling Stream Data: dev/stream_client/data-handling.md
          - Block Range Parameters: dev/stream_client/block-ranges.md
          - Browser Usage: dev/stream_client/browser-usage.md
          - Error Handling: dev/stream_client/error-handling.md
      - Endpoint List: dev/endpoint.md
  - API Reference:
      - v2: api/v2.md
      - v1 compatible: api/v1.md
#  - FAQ: help/faq.md

plugins:
  - social:
      cards_layout_options:
        background_color: "#00B3FE"
        font_family: Ubuntu
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

theme:
  name: 'material'
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - navigation.footer
    - search.suggest
    - search.highlight
  language: en
  palette:
    primary: 'light blue'
    accent: 'orange'
  logo: 'assets/img/simplified_logo.svg'
  favicon: 'assets/img/icon.png'
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra:
  generator: false
  version:
    provider: mike
  analytics:
    provider: google
    property: G-N6WF1VPFSH
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/eosrio/hyperion-history-api'
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/eosrio/hyperion-docs'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/eosriobrazil'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/EOSHyperion'
